services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mindshape\MindshapeCookieConsent\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model,Utility}'

